### ISSUE TITLE
Fail to add ProcMon reporter

### ISSUE THREAD

**Issue by Q-Wednesday** [ashish-gehani/SPADE#111]
I tried to add a ProMon reporter like this:
-> add reporter ProcMon ./bin/test.CSV
Adding reporter ProcMon... failed

but it failed.
Here is the log:
java.lang.NullPointerException
	at spade.reporter.ProcMon.launch(ProcMon.java:120)
	at spade.core.Kernel.addReporterCommand(Kernel.java:1028)
	at spade.core.Kernel.addCommand(Kernel.java:1192)
	at spade.core.Kernel.executeCommand(Kernel.java:621)
	at spade.core.Kernel$LocalControlConnection.run(Kernel.java:2059)
	at java.base/java.lang.Thread.run(Thread.java:835)

May 23, 2021 9:18:30 PM spade.core.Kernel addReporterCommand Error: Unable to launch reporter

How can I solve this problem?

**Comment by hassaanirshad** [comment]
Thank you for sharing the error in the log.

Please pull the latest code from the `master` branch, and use that. It should help you identify the error.

About how to use the ProcMon reporter, please refer to the wiki page [here](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Windows).

**Comment by Q-Wednesday** [comment]
Thanks!
