### ISSUE TITLE
Query crashes / gets terminated automatically, once the maxDepth is set a bit high 

### ISSUE THREAD

**Issue by iai-rsa** [ashish-gehani/SPADE#129]
When querying for backward or forward tracing using **_getLineage()_**,  or for getting paths between two vertices using **_getPath()_**, the query tends to fail with an "incorrect" error message,  if the **_maxDepth_** parameter is set a bit high (>4).

**An example:** 

$lineage = $base.getLineage($vertex, 5, 'a')

Error: Error evaluating QuickGrail command:
_------------------------------------------------------------
The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. Explicitly terminated by the user. 
------------------------------------------------------------_

**Excerpt from the log file:**

spade.query.quickgrail.QuickGrailExecutor execute SEVERE: null

java.lang.RuntimeException: The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. Explicitly terminated by the user. 

        at spade.storage.Neo4j.executeQueryAndBlockForResult(Neo4j.java:755)

        at spade.storage.Neo4j.executeQueryForSmallResult(Neo4j.java:722)

        at spade.storage.Neo4j.executeQuery(Neo4j.java:717)

        at spade.storage.neo4j.Neo4jInstructionExecutor.getLineage(Neo4jInstructionExecutor.java:984)

        at spade.query.quickgrail.instruction.GetLineage.execute(GetLineage.java:104)

        at spade.query.quickgrail.instruction.GetLineage.execute(GetLineage.java:34)

        at spade.query.quickgrail.QuickGrailExecutor.execute(QuickGrailExecutor.java:91)

        at spade.analyzer.CommandLine$QueryConnection.executeQuery(CommandLine.java:227)

        at spade.core.AbstractAnalyzer$QueryConnection.run(AbstractAnalyzer.java:364)

        at java.base/java.lang.Thread.run(Thread.java:829)

Caused by: org.neo4j.graphdb.TransactionTerminatedException: The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. Explicitly terminated by the user. 

        at org.neo4j.kernel.impl.api.KernelTransactionImplementation.assertOpen(KernelTransactionImplementation.java:588)

        at org.neo4j.kernel.impl.newapi.Read.singleRelationship(Read.java:288)

        at org.neo4j.cypher.operations.CursorUtils.relationshipGetProperty(CursorUtils.java:243)

        at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$RelationshipOperations.getProperty(TransactionBoundQueryContext.scala:616)

        at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$RelationshipOperations.getProperty(TransactionBoundQueryContext.scala:592)

        at org.neo4j.cypher.internal.planning.ExceptionTranslatingQueryContext$ExceptionTranslatingOperations.getProperty(ExceptionTranslatingQueryContext.scala:327)

        at org.neo4j.cypher.internal.runtime.interpreted.DelegatingOperations.getProperty(DelegatingQueryContext.scala:331)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.Property.apply(Property.scala:55)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.StringOperator.isMatch(Predicate.scala:291)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.StringOperator.isMatch$(Predicate.scala:291)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.Contains.isMatch(Predicate.scala:319)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.InList.$anonfun$isMatch$1(InList.scala:55)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.AllInList.forAll(InList.scala:83)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.AllInList.$anonfun$seqMethod$1(InList.scala:92)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.InList.isMatch(InList.scala:53)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.CompositeBooleanPredicate.$anonfun$isMatch$2(Predicate.scala:95)

        at scala.util.Try$.apply(Try.scala:213)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.CompositeBooleanPredicate.$anonfun$isMatch$1(Predicate.scala:95)

        at org.neo4j.cypher.internal.util.NonEmptyList.foldLeftLoop(NonEmptyList.scala:284)

        at org.neo4j.cypher.internal.util.NonEmptyList.foldLeft(NonEmptyList.scala:205)

        at org.neo4j.cypher.internal.util.NonEmptyList.foldLeft$(NonEmptyList.scala:204)

        at org.neo4j.cypher.internal.util.Fby.foldLeft(NonEmptyList.scala:360)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.CompositeBooleanPredicate.isMatch(Predicate.scala:90)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.Predicate.apply(Predicate.scala:53)

        at org.neo4j.cypher.internal.runtime.interpreted.commands.predicates.Predicate.apply(Predicate.scala:51)

        at org.neo4j.cypher.internal.runtime.interpreted.pipes.FilterPipe.$anonfun$internalCreateResults$1(FilterPipe.scala:31)

        at org.neo4j.cypher.internal.runtime.interpreted.pipes.FilterPipe.$anonfun$internalCreateResults$1$adapted(FilterPipe.scala:31)

        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:513)

        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)

        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)

        at org.neo4j.cypher.internal.runtime.interpreted.pipes.EmptyResultPipe.internalCreateResults(EmptyResultPipe.scala:28)

        at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:70)

        at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:66)

        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:59)

        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:99)

        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.initiate(StandardInternalExecutionResult.scala:62)

        at org.neo4j.cypher.internal.result.ClosingExecutionResult.$anonfun$initiate$1(ClosingExecutionResult.scala:59)

        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

        at org.neo4j.cypher.internal.result.ClosingExecutionResult.safely(ClosingExecutionResult.scala:100)

        at org.neo4j.cypher.internal.result.ClosingExecutionResult.initiate(ClosingExecutionResult.scala:59)

        at org.neo4j.cypher.internal.result.ClosingExecutionResult$.wrapAndInitiate(ClosingExecutionResult.scala:189)

        at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.innerExecute(CypherCurrentCompiler.scala:354)

        at org.neo4j.cypher.internal.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:291)

        at org.neo4j.cypher.internal.ExecutionEngine.doExecute(ExecutionEngine.scala:219)

        at org.neo4j.cypher.internal.ExecutionEngine.$anonfun$executeSubQuery$1(ExecutionEngine.scala:180)

        at org.neo4j.cypher.internal.ExecutionEngine.closing(ExecutionEngine.scala:185)

        at org.neo4j.cypher.internal.ExecutionEngine.executeSubQuery(ExecutionEngine.scala:177)

        at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:127)

        at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:122)

        at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:111)

        at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:236)

        at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:225)

        at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:219)

        at spade.storage.neo4j.TaskExecuteQuery.execute(TaskExecuteQuery.java:49)

        at spade.storage.neo4j.TaskExecuteQuery.execute(TaskExecuteQuery.java:31)

        at spade.storage.Neo4j$1.run(Neo4j.java:521)

        ... 1 more

**Comment by ashish-gehani** [comment]
This is an exception from the underlying database, Neo4j. You can file a report at their site.
