### ISSUE TITLE
Unable to remove reporter and storage

### ISSUE THREAD

**Issue by chelun-c000** [ashish-gehani/SPADE#136]
I have been troubled by this issue for a long time and would appreciate it if you could help me determine whether there are any issues with my operations. Thank you! :) (I use Ubuntu 23.)

I sequentially entered the following commands in the control panel:
```
add storage Prov output=/tmp/provenance.ttl audit=http://spade.csl.sri.com/rdf/audit.rdfs
add filter OPM2Prov position=1
add reporter Audit
```
All results were displayed as successful. I then performed various actions on the computer (compiling C language files, git clone, push, etc.) to generate some audit logs. After completing these operations, I entered **remove storage Prov** (or **remove reporter Audit**) in the control panel. At this point, SPADE became unresponsive. I subsequently exited and attempted to stop SPADE. However, upon checking the spade status, I discovered that SPADE's status remained as "running."

I have tried this process numerous times before and noticed that whenever I use the **remove storage Prov** command, there is no response, leading to subsequent issues. I would like to inquire if there might be a problem with the order of my operations.

Additionally, I would like to know why there have been no records generated in the **/tmp/provenance** file. Could you please help identify the possible reasons for this issue?

Here is the log when I entered **remove reporter Audit**, and SPADE became unresponsive:
[current.log](https://github.com/ashish-gehani/SPADE/files/13523678/current.log)

![image](https://github.com/ashish-gehani/SPADE/assets/58452858/3ce1549e-9636-40d7-876a-584b7c111dd4)

**Comment by ashish-gehani** [comment]
`add filter OPM2Prov position=1`

did not succeed.

See:

`Dec 01, 2023 5:37:19 PM spade.core.Kernel$1 run SEVERE: Error registering Main Thread
java.lang.NullPointerException
	at spade.filter.OPM2ProvVertexEdge.createProvVertex(OPM2ProvVertexEdge.java:80)
	at spade.filter.OPM2ProvVertexEdge.putVertex(OPM2ProvVertexEdge.java:40)
	at spade.filter.OPM2Prov.putVertex(OPM2Prov.java:58)
	at spade.core.Kernel$1.run(Kernel.java:506)
	at java.base/java.lang.Thread.run(Thread.java:829)`
